name: flutter_datenbank_isar
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  isar: ^3.1.0+1 # Isar database package
  isar_flutter_libs: ^3.1.0+1 # Enthalt die Bin채rdateien f체r Isar
  path_provider: ^2.1.5 # Zugriff auf den Dateispeicher des Ger채ts
  provider: ^6.1.3 # State Management


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
isar_generator: ^3.1.0+1 # Isar Code-Generator f체r die Datenbankmodelle


flutter:


  uses-material-design: true


